# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a326408a832f918e4c3bf994100c712fc46c2d8a728af697575f3cfc7f38ab40a53bcb6df053ed2804ece3e679bbc0709556fcd28a1ff36b56aa21486296027b

test:
  secret_key_base: 3f276335230d0339e8618f8f364605949466f23c0218c692624aa1b30860f86fdf722c12515742c2a7029a92a1847c5a896afb989a6340280e92da9c0d3560fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
